name: machinelearning
channels:
  - conda-forge
  - omnia
dependencies:
  - pip
  - netcdf4
  - ipykernel
  - scipy
  - numpy
  - mdtraj
  - python=3.7
  - openmm
  - openmmtools
  - nglview
  - parmed
  - mdanalysis
  - pip:
      - tensorflow
      - tensorflow-probability
#After done, need to install Frank Noe's deep_boltzmann package
#Find directory where pulled and run `pip install -e .` where there is a setup.py present
